name = "CMAQ"
uuid = "1d6620e0-af0f-4aad-99b8-8210b6260ab1"
authors = ["US EPA and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
