name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - gcc${{matrix.gcc}} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
#          - windows-latest
        arch:
          - x64
        gcc:
          - 7
          - 8
          - 9
          - 10
        exclude:
          - gcc: 8
            version: "1.6"
          - gcc: 9
            version: "1.6"
          - gcc: 10
            version: "1.6"
          - gcc: 7
            version: "nightly"
    steps:
      - name: Install Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install gcc-${{ matrix.gcc }} gfortran-${{ matrix.gcc }} tcsh
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install gcc@${{ matrix.gcc }} tcsh
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "Windows"
          fi
        shell: bash
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
          CC: gcc-${{ matrix.gcc }}
          CXX: g++-${{ matrix.gcc }}
          FC: gfortran-${{ matrix.gcc }}
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info